name: Deploys preview to Vercel

on:
  push:
    branches:
      - dev

  workflow_dispatch:

concurrency: development

# Deploy preview to Vercel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.vercel-deploy.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
